#ifndef SLIPSTREAM5000_ACTOR_FORMAT_H
#define SLIPSTREAM5000_ACTOR_FORMAT_H

/* Byte offsets in serialized ART resources, not native structure offsets. */
enum {
	SLIP_ART_HEADER_BYTES = 0x68,
	/* Vehicle previews accept the shorter header used by their original loader. */
	SLIP_ART_PREVIEW_HEADER_BYTES = 0x58,
	/* Coordinates within the serialized three-dword positions and bounds. */
	SLIP_ART_POSITION_X_OFFSET = 0,
	SLIP_ART_POSITION_Y_OFFSET = 4,
	SLIP_ART_POSITION_Z_OFFSET = 8,
	SLIP_ART_MINIMUM_OFFSET = 4,
	SLIP_ART_MAXIMUM_OFFSET = 0x10,
	SLIP_ART_ROOT_PART_OFFSET = 0x20,
	SLIP_ART_SORT_CHILDREN_OFFSET = 0x24,
	SLIP_ART_LOD_DISTANCES_OFFSET = 0x28,
	SLIP_ART_REPLAY_LOD_DISTANCES_OFFSET = 0x48,
	SLIP_ART_LOD_COUNT = 8,
	SLIP_ART_DISTANCE_BYTES = 4,
	SLIP_ART_PART_CHILD_OFFSET = 4,
	SLIP_ART_PART_SIBLING_OFFSET = 8,
	SLIP_ART_PART_ROTATION_CALLBACK_OFFSET = 0xc,
	/* Serialized rotation callback offsets index four-byte table entries. */
	SLIP_ART_ROTATION_CALLBACK_ENTRY_BYTES = 4,
	SLIP_ART_PART_POSITION_OFFSET = 0x10,
	SLIP_ART_PART_SHAPE_NAMES_OFFSET = 0x1c,
	SLIP_ART_PART_REPLAY_SHAPE_NAMES_OFFSET = 0x8c,
	SLIP_ART_PART_DESTRUCTION_OFFSET = 0xfc,
	SLIP_ART_PART_DEBRIS_OFFSET = 0x164,
	SLIP_ART_PART_POINT_COUNT_OFFSET = 0x1cc,
	SLIP_ART_PART_POINTS_OFFSET = 0x1d0,
	SLIP_ART_SHAPE_NAME_BYTES = 14,
	SLIP_ART_DESTRUCTION_COUNT = 4,
	SLIP_ART_DEBRIS_COUNT = 4,
	SLIP_ART_NAMED_SHAPE_BYTES = 26,
	SLIP_ART_NAMED_SHAPE_POSITION_OFFSET = 14,
	SLIP_ART_POINT_CAPACITY = 5,
	SLIP_ART_POINT_BYTES = 16,
	SLIP_ART_POINT_POSITION_OFFSET = 4
};

/* Original pool allocation sizes; native records contain host pointers. */
enum {
	SLIP_ACTOR_DEFAULT_PART_CAPACITY = 80,
	SLIP_ACTOR_RECORD_DOS_BYTES = 0xd8,
	SLIP_ACTOR_PART_DOS_BYTES = 0x160,
	SLIP_ACTOR_POOL_SENTINEL_COUNT = 2,
	SLIP_ACTOR_PART_POOL_SENTINEL_COUNT = 1
};

/* Actor part arrays reserve the final slot for the last successful tag lookup. */
enum { SLIP_ACTOR_CACHED_PART_INDEX = 16, SLIP_ACTOR_PART_SLOT_COUNT = SLIP_ACTOR_CACHED_PART_INDEX + 1 };

#endif
