#ifndef SLIPSTREAM5000_ARCHIVE_FORMAT_H
#define SLIPSTREAM5000_ARCHIVE_FORMAT_H

#include <stdint.h>

/* Serialized RES directory records. The name field is XORed when the high
 * bit of the directory count is set; its first twelve bytes hold an 8.3 name. */
enum {
	SLIP_ARCHIVE_INDEX_OFFSET_BYTES = sizeof(uint32_t),
	SLIP_ARCHIVE_INDEX_NAME_BYTES = 16,
	SLIP_ARCHIVE_ENTRY_FILE_KIND = 2,
	SLIP_ARCHIVE_ENTRY_NAME_OFFSET = 4,
	SLIP_ARCHIVE_ENTRY_PAYLOAD_OFFSET = SLIP_ARCHIVE_ENTRY_NAME_OFFSET + SLIP_ARCHIVE_INDEX_NAME_BYTES,
	SLIP_ARCHIVE_ENTRY_PAYLOAD_SIZE_OFFSET = SLIP_ARCHIVE_ENTRY_PAYLOAD_OFFSET + sizeof(uint32_t),
	SLIP_ARCHIVE_ENTRY_BYTES = SLIP_ARCHIVE_ENTRY_PAYLOAD_SIZE_OFFSET + sizeof(uint32_t)
};

#define SLIP_ARCHIVE_COUNT_ENCRYPTED UINT32_C(0x80000000)

#endif
