#ifndef SLIPSTREAM5000_CHAMPIONSHIP_SAVE_FORMAT_H
#define SLIPSTREAM5000_CHAMPIONSHIP_SAVE_FORMAT_H

#include <stdint.h>

/* SLIPSTRM.SAV directory layout and its fixed number of save slots. */
enum {
	SLIP_SAVE_DIRECTORY_VERSION = 2,
	SLIP_SAVE_SLOT_COUNT = 6,
	SLIP_SAVE_NAME_BYTES = 32,
	SLIP_SAVE_DIRECTORY_HEADER_BYTES = 4,
	SLIP_SAVE_DIRECTORY_ENTRY_BYTES = SLIP_SAVE_NAME_BYTES + 2 * sizeof(uint16_t)
};

#endif
