#ifndef SLIPSTREAM5000_FONT_FORMAT_H
#define SLIPSTREAM5000_FONT_FORMAT_H

/* FONT resource header and glyph table entries. */
enum {
	SLIP_FONT_SIGNATURE_BYTES = 4,
	SLIP_FONT_WIDTH_OFFSET = 4,
	SLIP_FONT_HEIGHT_OFFSET = 6,
	SLIP_FONT_FIRST_CHARACTER_OFFSET = 8,
	SLIP_FONT_LAST_CHARACTER_OFFSET = 9,
	SLIP_FONT_TABLE_OFFSET = 10,
	SLIP_FONT_HEADER_BYTES = 14,
	SLIP_FONT_GLYPH_ENTRY_BYTES = 4,
	SLIP_FONT_GLYPH_ADVANCE_OFFSET = 2
};

#endif
