#ifndef SLIPSTREAM5000_MATERIAL_FORMAT_H
#define SLIPSTREAM5000_MATERIAL_FORMAT_H

/* Serialized MAT records. Runtime material records have a separate layout. */
enum {
	SLIP_MAT_VERSION = 1,
	SLIP_MAT_VERSION_OFFSET = 2,
	SLIP_MAT_HEADER_BYTES = 4,
	SLIP_MAT_RECORD_BYTES = 46,
	SLIP_MAT_NAME_BYTES = 16,
	SLIP_MAT_RAMP_START_OFFSET = 16,
	SLIP_MAT_RAMP_END_OFFSET = 17,
	SLIP_MAT_IMPORTED_BYTE_OFFSET = 18,
	SLIP_MAT_VERTEX_SHADING_OFFSET = 19,
	SLIP_MAT_TRANSPARENCY_OFFSET = 20,
	SLIP_MAT_SKIP_FLAT_OFFSET = 21,
	SLIP_MAT_FIXED_SHADE_OFFSET = 22,
	SLIP_MAT_AMBIENT_OFFSET = 24,
	SLIP_MAT_DIFFUSE_OFFSET = 26,
	SLIP_MAT_SPECULAR_OFFSET = 28,
	SLIP_MAT_DITHER_BITS_OFFSET = 30,
	SLIP_MAT_TEXTURE_NAME_OFFSET = 34,
	SLIP_MAT_TEXTURE_NAME_BYTES = 12,
	/* The dot and three extension characters retained after a wildcard. */
	SLIP_MAT_TEXTURE_SUFFIX_BYTES = 4,
	SLIP_MAT_DITHER_SHIFT_MASK = 31,
	SLIP_MAT_MAXIMUM_RAMP_RANGE = 112
};

#endif
