#ifndef SLIPSTREAM5000_MENU_PALETTE_H
#define SLIPSTREAM5000_MENU_PALETTE_H

/* Palette indices used by the menu and results artwork. */
enum {
	SLIP_MENU_PANEL_LEFT_COLOUR = 0x25,
	SLIP_MENU_PANEL_TOP_COLOUR = 0x2b,
	SLIP_MENU_PANEL_SHADOW_COLOUR = 0x0a,
	SLIP_MENU_CONTROL_SELECTION_COLOUR = 0x37,
	SLIP_MENU_CONTROL_LABEL_COLOUR = 0x18,
	SLIP_MENU_CONTROL_BUTTON_LEFT_COLOUR = 0xa4,
	SLIP_MENU_CONTROL_BUTTON_TOP_COLOUR = 0xa5,
	SLIP_MENU_CONTROL_BUTTON_RIGHT_COLOUR = 0x8c,
	SLIP_MENU_CONTROL_BUTTON_BOTTOM_COLOUR = 0x8b,
	SLIP_MENU_CONTROL_MESSAGE_COLOUR = 0xff
};

#endif
