#ifndef SLIPSTREAM5000_RACE_LIMITS_H
#define SLIPSTREAM5000_RACE_LIMITS_H

enum {
	SLIP_RACE_RACER_COUNT = 10,
	/* Driver-indexed tables reserve slot zero. */
	SLIP_RACE_DRIVER_TABLE_COUNT = SLIP_RACE_RACER_COUNT + 1
};

typedef enum SlipRaceTrackId {
	SLIP_RACE_TRACK_CHICAGO = 1,
	SLIP_RACE_TRACK_HAWAII,
	SLIP_RACE_TRACK_TOKYO,
	SLIP_RACE_TRACK_NORWAY,
	SLIP_RACE_TRACK_CAVE,
	SLIP_RACE_TRACK_CANADA,
	SLIP_RACE_TRACK_AMAZON,
	SLIP_RACE_TRACK_LONDON,
	SLIP_RACE_TRACK_EGYPT,
	SLIP_RACE_TRACK_NEW_YORK,
	SLIP_RACE_TRACK_COUNT = SLIP_RACE_TRACK_NEW_YORK,
} SlipRaceTrackId;

enum { SLIP_RACE_TRACK_TABLE_COUNT = SLIP_RACE_TRACK_COUNT + 1 };

#endif
