#ifndef SLIPSTREAM5000_RACE_TIME_FORMAT_H
#define SLIPSTREAM5000_RACE_TIME_FORMAT_H

/* HH:MM:SS:hh, where the final pair is hundredths of a second. */
enum {
	SLIP_RACE_TIME_MILLISECONDS_PER_SECOND = 1000,
	SLIP_RACE_TIME_MILLISECONDS_PER_MINUTE = 60 * SLIP_RACE_TIME_MILLISECONDS_PER_SECOND,
	SLIP_RACE_TIME_MILLISECONDS_PER_HOUR = 60 * SLIP_RACE_TIME_MILLISECONDS_PER_MINUTE,
	SLIP_RACE_TIME_MILLISECONDS_PER_HUNDREDTH = SLIP_RACE_TIME_MILLISECONDS_PER_SECOND / 100,
	SLIP_RACE_TIME_FIELD_COUNT = 4,
	SLIP_RACE_TIME_FIELD_DIGITS = 2,
	SLIP_RACE_TIME_FIELD_STRIDE = SLIP_RACE_TIME_FIELD_DIGITS + 1,
	SLIP_RACE_TIME_TEXT_BYTES = SLIP_RACE_TIME_FIELD_COUNT * SLIP_RACE_TIME_FIELD_STRIDE,
	SLIP_RACE_TIME_MINUTES_OFFSET = SLIP_RACE_TIME_FIELD_STRIDE,
	SLIP_RACE_TIME_MINUTES_SEPARATOR = SLIP_RACE_TIME_MINUTES_OFFSET + SLIP_RACE_TIME_FIELD_DIGITS,
	SLIP_RACE_TIME_SECONDS_SEPARATOR = 2 * SLIP_RACE_TIME_FIELD_STRIDE + SLIP_RACE_TIME_FIELD_DIGITS
};

#endif
