#ifndef SLIPSTREAM5000_RENDERER_FLAGS_H
#define SLIPSTREAM5000_RENDERER_FLAGS_H

/* Texture mode retains masked textures only for the fine texture setting. */
enum { SLIP_RENDER_TEXTURE_MASKING_ENABLED = 0, SLIP_RENDER_TEXTURE_MASKING_DISABLED = 1 };

enum {
	SLIP_VERTEX_TRANSFORMED = 0x0001u,
	SLIP_VERTEX_PROJECTED = 0x0002u,
	SLIP_VERTEX_DEPTH_CLASSIFIED = 0x0004u,
	SLIP_VERTEX_TRANSFORMED_AND_DEPTH_CLASSIFIED = SLIP_VERTEX_TRANSFORMED | SLIP_VERTEX_DEPTH_CLASSIFIED,
	SLIP_VERTEX_VIEW_MASK_CLASSIFIED = 0x0800u,
	SLIP_VERTEX_DEPTH_BLEND_CACHED = 0x0400u,
	SLIP_CLIP_LEFT = 0x0008u,
	SLIP_CLIP_RIGHT = 0x0010u,
	SLIP_CLIP_TOP = 0x0020u,
	SLIP_CLIP_BOTTOM = 0x0040u,
	SLIP_CLIP_NEAR = 0x0080u,
	SLIP_CLIP_FAR = 0x0100u,
	SLIP_VERTEX_SCREEN_CLIP_IN_RANGE = 0x0200u,
	SLIP_CLIP_AUXILIARY = 0x2000u,
	SLIP_CLIP_HORIZONTAL = SLIP_CLIP_LEFT | SLIP_CLIP_RIGHT,
	SLIP_CLIP_VERTICAL = SLIP_CLIP_TOP | SLIP_CLIP_BOTTOM,
	SLIP_CLIP_SCREEN = SLIP_CLIP_HORIZONTAL | SLIP_CLIP_VERTICAL,
	SLIP_CLIP_DEPTH = SLIP_CLIP_NEAR | SLIP_CLIP_FAR,
	SLIP_CLIP_BEFORE_PROJECTION = SLIP_CLIP_DEPTH | SLIP_CLIP_AUXILIARY,
	SLIP_CLIP_ALL = SLIP_CLIP_SCREEN | SLIP_CLIP_BEFORE_PROJECTION,

	SLIP_VERTEX_VERTICAL_CLIP_STATUS = SLIP_CLIP_VERTICAL | SLIP_VERTEX_SCREEN_CLIP_IN_RANGE,

	SLIP_SHAPE_SHORT_COORDINATES = 0x0001u,
	SLIP_SHAPE_INSIDE_VIEW = 0x0002u,
	SLIP_SHAPE_CLIP_AUXILIARY = 0x0004u,
	SLIP_SHAPE_FORCE_SECONDARY_PROJECTION = 0x0008u,
	SLIP_SHAPE_SECONDARY_PROJECTION = SLIP_SHAPE_INSIDE_VIEW | SLIP_SHAPE_FORCE_SECONDARY_PROJECTION,

	/* Bounds classifiers use four screen bits, separate from vertex status flags. */
	SLIP_BOUNDS_CLIP_LEFT = 1u,
	SLIP_BOUNDS_CLIP_RIGHT = 2u,
	SLIP_BOUNDS_CLIP_BOTTOM = 4u,
	SLIP_BOUNDS_CLIP_TOP = 8u,

	SLIP_BOX_CLIP_NEAR = 0x10u,
	SLIP_BOX_CLIP_FAR = 0x20u,
	SLIP_BOX_CLIP_AUXILIARY = 0x40u,

	SLIP_SCREEN_CLIP_COORDINATE_LIMIT = 0x3ffe,
	SLIP_INTERPOLATE_PERSPECTIVE_DEPTH = 1u,
	SLIP_INTERPOLATE_TEXTURE = 2u,
	SLIP_INTERPOLATE_TEXTURE_PERSPECTIVE = SLIP_INTERPOLATE_PERSPECTIVE_DEPTH | SLIP_INTERPOLATE_TEXTURE,
	SLIP_INTERPOLATE_SHADE = 4u,
	SLIP_RENDER_WIREFRAME = 1u,
	SLIP_RENDER_FLAT_SHADING = 2u,
	SLIP_RENDER_DISABLE_VERTEX_SHADING = SLIP_RENDER_WIREFRAME | SLIP_RENDER_FLAT_SHADING,
	SLIP_POLYGON_COLOUR_VERTEX_SHADED = 0x8000u,
	SLIP_POLYGON_DRAW_FLAT = 0,
	SLIP_POLYGON_DRAW_LINE = 2,
	SLIP_POLYGON_DRAW_TEXTURED = 3,
	SLIP_RENDER_DISABLE_TEXTURES = 8u,
	SLIP_RENDER_DISABLE_SPECULAR = 4u,
	SLIP_RENDER_SOLID_TEXTURE_FALLBACK = SLIP_RENDER_WIREFRAME | SLIP_RENDER_DISABLE_TEXTURES,
	SLIP_RENDER_MASKED_TEXTURE = 0x10u,
	SLIP_POLYGON_RECTANGLE_VERTICES = 4,
	SLIP_SHADE_COLOUR_SHIFT = 8,
	SLIP_POLYGON_DRAW_SHADED = 1,
	SLIP_POLYGON_DRAW_DITHERED = 4,
	SLIP_POST_PLANE_DISTANCE_SHIFT = 2,
	SLIP_BYTE_BITS = 8,
	SLIP_WORD_BITS = 16,
	SLIP_DWORD_SHIFT_COUNT_MASK = 31,
	SLIP_PROJECTION_SLOPE_FRACTION_BITS = 16,
	SLIP_CLIP_FRACTION_BITS = 14,
	SLIP_CLIP_ROUND_BIT = SLIP_CLIP_FRACTION_BITS - 1,
	SLIP_CLIP_PRECISE_FRACTION_BITS = 30,
	SLIP_CLIP_PRECISE_ROUND_BIT = SLIP_CLIP_PRECISE_FRACTION_BITS - 1,
	SLIP_NORMAL_FRACTION_BITS = 14,
	SLIP_LIGHT_UNIT = 1u << SLIP_NORMAL_FRACTION_BITS,
	SLIP_SPECULAR_WORD_INDEX_MASK = 0x7fffu,
	SLIP_NORMAL_ROUND_BIT = SLIP_NORMAL_FRACTION_BITS - 1
};
#endif
