#ifndef SLIPSTREAM5000_SHAPE_FORMAT_H
#define SLIPSTREAM5000_SHAPE_FORMAT_H

enum {
	SLIP_PRIMITIVE_COUNT_FLAGS_OFFSET = 0,
	SLIP_PRIMITIVE_NORMAL_X_OFFSET = 2,
	SLIP_PRIMITIVE_NORMAL_Y_OFFSET = 4,
	SLIP_PRIMITIVE_NORMAL_Z_OFFSET = 6,
	SLIP_PRIMITIVE_MATERIAL_OFFSET = 8,
	SLIP_PRIMITIVE_RENDER_FLAGS_OFFSET = 10,
	SLIP_PRIMITIVE_HEADER_BYTES = 12,
	SLIP_PRIMITIVE_SKIP_RENDER = 4u,
	SLIP_PRIMITIVE_VERTEX_COUNT_MASK = 0x3fffu,
	SLIP_PRIMITIVE_VERTEX_NORMALS = 0x4000u,
	SLIP_PRIMITIVE_TEXTURE_COORDINATES = 0x8000u,
	SLIP_PRIMITIVE_SOLID_COUNT_FLAGS_MASK = SLIP_PRIMITIVE_VERTEX_COUNT_MASK | SLIP_PRIMITIVE_VERTEX_NORMALS,
	SLIP_PRIMITIVE_EXTENDED = SLIP_PRIMITIVE_VERTEX_NORMALS | SLIP_PRIMITIVE_TEXTURE_COORDINATES,
	SLIP_SHAPE_MATERIALS_PREPARED = 1u,
	SLIP_SHAPE_FLAGS_OFFSET = 4,

	SLIP_DEFAULT_TEXTURE_DISPATCH_THRESHOLD = 0x6b3a0,

	SLIP_RENDER_ALTERNATE_TEXTURE_RASTER = 0x20u,
	SLIP_TEXTURE_AFFINE_FACING_THRESHOLD = -16380,
	SLIP_SERIALIZED_INDEX_BYTES = 2,
	SLIP_SERIALIZED_NORMAL_BYTES = 6,
	SLIP_SERIALIZED_NORMAL_X_OFFSET = 0,
	SLIP_SERIALIZED_NORMAL_Y_OFFSET = 2,
	SLIP_SERIALIZED_NORMAL_Z_OFFSET = 4,
	SLIP_SERIALIZED_TEXTURE_COORDINATE_BYTES = 4
};
#endif
