#ifndef SLIPSTREAM5000_SPRITE_FORMAT_H
#define SLIPSTREAM5000_SPRITE_FORMAT_H

/* Byte offsets in serialized SPR resources and their palette packets. */
enum {
	SLIP_SPRITE_WIDTH_OFFSET = 0,
	SLIP_SPRITE_HEIGHT_OFFSET = 2,
	SLIP_SPRITE_DIMENSIONS_END = SLIP_SPRITE_HEIGHT_OFFSET + 2,
	SLIP_SPRITE_X_OFFSET = 4,
	SLIP_SPRITE_Y_OFFSET = 6,
	SLIP_SPRITE_TRANSPARENT_COLOUR_OFFSET = 8,
	SLIP_SPRITE_TRANSPARENT_COLOUR_END = SLIP_SPRITE_TRANSPARENT_COLOUR_OFFSET + 2,
	SLIP_SPRITE_NO_TRANSPARENT_COLOUR = 0xffff,
	SLIP_SPRITE_PALETTE_OFFSET = 14,
	SLIP_SPRITE_HEADER_BYTES = 16,
	SLIP_PALETTE_START_OFFSET = 0,
	SLIP_PALETTE_COUNT_OFFSET = 2,
	SLIP_PALETTE_HEADER_BYTES = 4,
	SLIP_PALETTE_RGB_BYTES = 3,
	SLIP_PALETTE_GREYSCALE_LEVELS = 64,
	SLIP_SPRITE_USE_STORED_POSITION = 0x7fff
};

#endif
