"""Rebuild the embedded GPU shaders (requires DXC and glslangValidator)."""
import argparse
from pathlib import Path
import subprocess
import tempfile

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--dxc', default='dxc')
parser.add_argument('--glslang', default='glslangValidator')
parser.add_argument('--clang-format', default='clang-format', help='Clang-format 22.1.3 executable')
args = parser.parse_args()
root = Path(__file__).resolve().parent
output = ['/* Generated by src/port/gpu/build_shaders.py. */', '#ifndef SLIP_GPU_SHADERS_H', '#define SLIP_GPU_SHADERS_H']
with tempfile.TemporaryDirectory() as temporary:
    for name, stage, profile in [('passthrough', 'vert', 'vs_6_0'), ('textured_dither', 'frag', 'ps_6_0')]:
        for format in ['dxil', 'spv', 'metal']:
            target = Path(temporary) / f'{name}.{stage}.{format}'
            if format == 'dxil':
                subprocess.run([args.dxc, '-T', profile, '-E', 'main', '-Fo', str(target), str(root / 'shaders' / f'{name}.{stage}.hlsl')], check=True)
            elif format == 'spv':
                subprocess.run([args.glslang, '-V', '-S', stage, '-o', str(target), str(root / 'shaders' / f'{name}.{stage}.glsl')], check=True)
            else:
                target.write_bytes((root / 'shaders' / f'{name}.{stage}.metal').read_bytes() + b'\0')
            data = target.read_bytes()
            output.append(f'static const unsigned char {name}_{stage}_{format}[] = {{')
            output.extend('\t' + ', '.join(f'0x{byte:02x}' for byte in data[i:i+16]) + ',' for i in range(0, len(data), 16))
            output.append('};')
output.append('#endif')
(root / 'shaders.h').write_text('\n'.join(output) + '\n')
subprocess.run([args.clang_format, '-i', str(root / 'shaders.h')], check=True)
